<%@LANGUAGE="VBSCRIPT" CODEPAGE="65001"%>
<!--#include file="../inc/xgconn.asp"-->
<%content=request("content")
contenten=request("contenten")
gsjsid=request("gsjsid")
type_wj=request("type_wj")
type_wjen=request("type_wjen")
t=request("t")
d=request("d")
k=request("k")
te=request("te")
de=request("de")
ke=request("ke")
txt2=request("txt2")
txt3=request("txt3")
txt2en=request("txt2en")
txt3en=request("txt3en")
pic1=request("pic1")
pic2=request("pic2")
pic3=request("pic3")
lpic1=request("lpic1")
lpic2=request("lpic2")
lpic3=request("lpic3")
links1=request("links1")
links2=request("links2")
links3=request("links3")
conn.execute"update gsjs set gsjstext='"&content&"',lpic1='"&lpic1&"',lpic3='"&lpic3&"',lpic2='"&lpic2&"',links1='"&links1&"',links3='"&links3&"',links2='"&links2&"',pic1='"&pic1&"',pic3='"&pic3&"',pic2='"&pic2&"',txt2='"&txt2&"',txt3='"&txt3&"',txt2en='"&txt2en&"',txt3en='"&txt3en&"',gsjstexten='"&contenten&"',type_wj='"&type_wj&"',type_wjen='"&type_wjen&"',t='"&t&"',d='"&d&"',k='"&k&"',te='"&te&"',de='"&de&"',ke='"&ke&"' where gsjsid="&gsjsid&""%>ok